-- Seed portfolio_projects table with data from portfolio-projects.json
-- Run with: sqlite3 journal.db < migrations/004_seed_portfolio_projects.sql

INSERT OR REPLACE INTO portfolio_projects (id, title, category, company, date_completed, status, featured, image, excerpt, description, role, technologies, metrics, links, tags, sort_order)
VALUES
-- AI Software (Featured)
('langfuse-refactor', 'Langfuse Prompt Management Infrastructure', 'AI Software', 'Jobilla DACH', '2025-10', 'shipped', 1, '/images/projects/langfuse.png', 'Built infrastructure enabling prompt updates without deployment, shipped to production across 12 endpoints', 'Architected comprehensive Langfuse prompt management system that transformed how we iterate on AI prompts. The system enables prompt updates without code deployment, tracks metrics by prompt version, and provides foundation for A/B testing. Learned the entire stack from zero, shipped it to production, and it works. Includes prompt version linking for data-driven optimization.', 'Lead engineer - designed architecture, implemented 12 endpoints, shipped 2 major releases', '["TypeScript", "Langfuse", "Vercel AI SDK", "Next.js", "OpenTelemetry"]', '{"endpoints": "12 endpoints migrated", "impact": "Enables data-driven prompt optimization without deployment"}', '{}', '["infrastructure", "ai", "production", "prompt-engineering"]', 1),

('campaign-labeling-pipeline', '26K Campaign Labeling Pipeline', 'AI Software', 'Jobilla DACH', '2025-09', 'shipped', 1, '/images/projects/data-pipeline.png', 'Python CLI tool for mass data labeling: 26K campaigns to ISCO, 7K companies to NACE classification', 'Built Python CLI tool enabling mass labeling and validation of campaign data for business intelligence and forecasting. The tool processes asynchronous operations, normalizes data, and uses well-prompted Gemini Flash for cost-effective structured outputs (99% reliability). Manual labeling would take thousands of human hours with high error rates. This pipeline cuts processing from hours to minutes while maintaining accuracy. Built the ''mother database'' that will power forecasting models.', 'Solo data engineer - designed pipeline, built CLI, validated results', '["Python", "Gemini Flash", "SQLite", "CLI", "Async Processing"]', '{"volume": "26K campaigns + 7K companies labeled", "accuracy": "99% reliability with structured LLM outputs", "cost": "Fraction of Amazon Turk cost"}', '{}', '["data-engineering", "python", "automation", "llm", "cli"]', 2),

('ai-image-pipeline', 'AI Image Generation Pipeline', 'AI Software', 'Jobilla DACH', '2024-12', 'shipped', 1, '/images/hero-ai.png', 'Internal tool that eliminated over €10,000 in annual Shutterstock costs', 'Engineered AI image-generation pipeline integrating Midjourney and Magnific upscaler, enabling marketing team to generate high-quality, royalty-free images on demand. The system eliminated annual stock photo subscription costs while providing more flexibility and faster turnaround than traditional stock imagery.', 'Lead engineer - architecture design, Python backend, team collaboration for requirements', '["Python", "Midjourney", "Magnific", "Imagen 3", "Laravel"]', '{"savings": "€10K+ annual cost elimination", "impact": "On-demand high-quality image generation"}', '{"live": "https://www.jobilla.com"}', '["ai", "cost-optimization", "image-generation", "automation"]', 3),

('job-application-intelligence', 'Job Application Intelligence (WIP)', 'AI Software', 'Personal Project', NULL, 'wip', 0, '/images/job-seeker-intelligence.png', 'Open-source web app for CV analysis and job matching (in development)', 'Open-source tool to help job seekers tailor applications effectively. Uses AI to analyze job descriptions and CVs, generating reports highlighting key matches and improvement areas. Goal is to democratize access to automated screening tools that large companies use. Currently in development.', 'Solo developer - concept to deployment (in progress)', '["Python", "Next.js", "TypeScript", "Docker", "Vercel", "OpenAI"]', '{}', '{}', '["ai", "open-source", "career", "wip"]', 4),

-- Web Design
('ngo-digital-toolkit', 'YEEI NGO Digital Toolkit', 'Web Design', 'Ouroboros Creative Collective', '2023-06', 'shipped', 1, '/images/hero-web.png', 'Multilingual Digital Marketing Communication toolkit deployed in 7+ languages across three continents', 'Designed and wrote comprehensive digital marketing communication toolkit for YEEI (international NGO). Hired as consultant to create toolkit covering narrative design, visual identity, and digital strategy. Deployed across three continents in over seven languages, designed for cultural adaptability. Includes content management guidance, social media templates, and brand guidelines.', 'Lead consultant - design, writing, project management, client collaboration', '["React", "Next.js", "TypeScript", "Vercel", "Figma", "Canva"]', '{"languages": "7+ languages", "reach": "Three continents"}', '{}', '["web", "design", "multilingual", "ngo", "content"]', 5),

('portfolio-website', 'This Portfolio Website', 'Web Design', 'Personal Project', '2025-10', 'shipped', 1, '/images/portfolio-meta.png', 'Built step by step with AI - multilingual Next.js 15 portfolio with structured data architecture', 'Built this portfolio website step by step using AI assistance, demonstrating modern web development practices and AI-assisted coding. Features multilingual support (EN/ES/FR/DE), structured data architecture for CV/projects/publications, dark/light theming, and responsive design. The site itself is a case study in resourceful building - vibe coding with serious intent, learning by shipping.', 'Solo developer - architecture, design, implementation, content', '["Next.js 15", "TypeScript", "Tailwind CSS", "Shadcn UI", "Vercel", "i18n"]', '{"languages": "4 languages supported", "approach": "AI-assisted, step-by-step building"}', '{"live": "https://guillermostumpf.com", "github": "https://github.com/yourusername/portfolio"}', '["web", "nextjs", "ai-assisted", "multilingual", "meta"]', 6),

('partner-website', 'Partner Website', 'Web Design', 'Ouroboros Creative Collective', '2025-08', 'shipped', 0, '/images/projects/partner-site.png', 'Modern web presence for creative partner', 'Built modern, responsive website for creative partner. Clean design, fast performance, mobile-first approach. Another example of resourceful web development - using modern frameworks to deliver professional results.', 'Web developer and designer', '["Next.js", "TypeScript", "Tailwind CSS", "Vercel"]', '{}', '{"live": "https://partner-site.com"}', '["web", "design", "freelance"]', 7),

('musician-website', 'Musician Website', 'Web Design', 'Ouroboros Creative Collective', '2025-09', 'shipped', 0, '/images/projects/musician-site.png', 'Portfolio and media hub for musician friend', 'Built portfolio website for musician friend, featuring media player, event calendar, and social media integration. Focus on visual storytelling and easy content updates. Clean, minimalist design that lets the music speak.', 'Web developer and designer', '["Next.js", "TypeScript", "Tailwind CSS", "Vercel"]', '{}', '{"live": "https://musician-site.com"}', '["web", "design", "freelance", "music"]', 8),

-- Graphic Design
('amz-marketing-infographics', 'Amazon Product Infographics', 'Graphic Design', 'AMZ-Marketing.de', '2022-09', 'shipped', 0, '/images/hero-design.png', 'Conversion-focused infographics for diverse B2B and B2C product portfolio on Amazon', 'Created conversion-focused infographics for wide range of Amazon products while working 20hrs/week alongside restaurant and university. Collaborated with account managers to ensure infographics effectively communicated key features and benefits. Adapted copy and images from established templates, meeting tight launch schedules while maintaining Amazon compliance. Gained experience in digital content creation pipelines.', 'Junior graphic designer - concept to final design', '["Canva", "Adobe Photoshop", "Midjourney", "Magnific"]', '{"schedule": "Daily graphics production", "workload": "20hrs/week freelance"}', '{}', '["design", "amazon", "canva", "infographics"]', 9),

-- Copywriting
('guacamole-website', 'Guacamole GmbH Website', 'Copywriting', 'Guacamole GmbH (via Ouroboros)', '2021-06', 'shipped', 0, '/images/portfolio-hero.png', 'Website copy for Mexican restaurant - my first professional copywriting work', 'My first professional copywriting project - created website copy for Guacamole GmbH through Ouroboros Creative Collective. This was where I discovered I could write for brands, translating restaurant atmosphere and values into web content. Simple but meaningful start to my content creation journey.', 'Copywriter - website content creation', '["HTML", "CSS", "Copywriting"]', '{}', '{"live": "https://guacamole-regensburg.de"}', '["copywriting", "web", "restaurant", "first-project"]', 10),

-- Movie & Animation
('short-film-1', 'Short Film Title 1', 'Movie & Animation', 'Personal Project', '2024-03', 'shipped', 1, '/images/movies/short-1.png', 'Short film - acting, writing, editing (local file, hosting TBD)', 'Complete short film project covering concept development, scriptwriting, acting, cinematography, and post-production. Demonstrates storytelling capabilities and multimedia production skills. Uses AI tools for enhancement and post-production workflows.', 'Writer, Director, Actor, Editor', '["Runway", "Premiere Pro", "After Effects", "Suno", "HeyGen"]', '{"duration": "TBD", "format": "Short film"}', '{"download": "/movies/short-film-1.mp4"}', '["movie", "acting", "editing", "storytelling"]', 11),

('short-film-2', 'Short Film Title 2', 'Movie & Animation', 'Personal Project', '2024-08', 'shipped', 0, '/images/movies/short-2.png', 'Short film - acting, writing, editing (local file, hosting TBD)', 'Second short film project exploring different storytelling techniques and visual styles. Continued experimentation with AI-assisted video generation and post-production workflows.', 'Writer, Director, Actor, Editor', '["Kling", "Sora", "DaVinci Resolve", "Suno"]', '{"duration": "TBD", "format": "Short film"}', '{"download": "/movies/short-film-2.mp4"}', '["movie", "acting", "editing", "storytelling"]', 12),

('youtube-showcase', 'YouTube Showcase', 'Movie & Animation', 'Personal Project', '2024-12', 'shipped', 1, '/images/movies/youtube-thumb.png', 'Video content showcase on YouTube - multimedia production capabilities', 'Collection of video content demonstrating range of multimedia production skills. Includes various formats: narrative shorts, experimental pieces, and behind-the-scenes content. Shows evolution of video production skills and experimentation with cutting-edge AI tools.', 'Producer, Editor, Content Creator', '["Runway", "Kling", "Premiere Pro", "After Effects", "Cinema 4D"]', '{}', '{"youtube": "https://youtube.com/@yourusername"}', '["movie", "youtube", "content-creation", "multimedia"]', 13);
