-- FORTRESS-001: Postgres mirror of Tartarus SQLite vault
-- Generated by web/scripts/fortress-sqlite-to-pg.mjs — do not hand-edit; regenerate instead
-- Source: /Users/guillermo.as/Documents/Software/Laboratory/tartarus/data/journal.db
-- Generated: 2026-07-01T10:13:54.195Z

CREATE TABLE IF NOT EXISTS fortress_sync_meta (
  id BIGSERIAL PRIMARY KEY,
  table_name TEXT NOT NULL UNIQUE,
  sqlite_row_count INTEGER,
  pushed_row_count INTEGER,
  last_pushed_at TIMESTAMPTZ DEFAULT NOW(),
  checksum TEXT
);

-- ai_artifacts
CREATE TABLE IF NOT EXISTS ai_artifacts (
      id BIGSERIAL PRIMARY KEY,
      integration_key TEXT NOT NULL,
      kind TEXT NOT NULL,
      source_path TEXT NOT NULL,
      title TEXT NOT NULL,
      summary TEXT,
      content TEXT,
      metadata TEXT DEFAULT '{}',
      content_hash TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(integration_key, kind, source_path)
    );
-- ai_integrations
CREATE TABLE IF NOT EXISTS ai_integrations (
      key TEXT PRIMARY KEY,
      display_name TEXT NOT NULL,
      status TEXT NOT NULL,
      version TEXT,
      auth_status TEXT,
      source_paths TEXT DEFAULT '[]',
      config_summary TEXT,
      metadata TEXT DEFAULT '{}',
      last_scanned_at TEXT
    );
-- ai_log_events
CREATE TABLE IF NOT EXISTS ai_log_events (
      id BIGSERIAL PRIMARY KEY,
      session_id INTEGER NOT NULL,
      sequence INTEGER NOT NULL,
      timestamp TEXT,
      actor TEXT NOT NULL,
      event_type TEXT NOT NULL,
      text TEXT NOT NULL,
      tooling TEXT,
      params TEXT DEFAULT '{}',
      source_event_type TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(session_id, sequence)
    );
-- ai_log_sessions
CREATE TABLE IF NOT EXISTS ai_log_sessions (
      id BIGSERIAL PRIMARY KEY,
      integration_key TEXT NOT NULL,
      stable_id TEXT NOT NULL,
      source_path TEXT NOT NULL,
      title TEXT NOT NULL,
      summary TEXT,
      started_at TEXT,
      updated_at TEXT,
      message_count INTEGER DEFAULT 0,
      metadata TEXT DEFAULT '{}',
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(integration_key, stable_id, source_path)
    );
-- ai_prompt_active
CREATE TABLE IF NOT EXISTS ai_prompt_active (
      prompt_slug TEXT PRIMARY KEY,
      version     INTEGER NOT NULL,
      updated_at  TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );
-- ai_prompt_versions
CREATE TABLE IF NOT EXISTS ai_prompt_versions (
      id          BIGSERIAL PRIMARY KEY,
      prompt_slug TEXT    NOT NULL,
      version     INTEGER NOT NULL,
      content     TEXT    NOT NULL,
      config      TEXT    NOT NULL DEFAULT '{}',
      label       TEXT    NOT NULL DEFAULT 'draft',
      created_at  TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP),
      created_by  TEXT    NOT NULL DEFAULT 'system',
      UNIQUE(prompt_slug, version)
    );
-- ai_proposals
CREATE TABLE IF NOT EXISTS ai_proposals (
      id BIGSERIAL PRIMARY KEY,
      integration_key TEXT NOT NULL,
      target_kind TEXT NOT NULL,
      target_path TEXT NOT NULL,
      title TEXT NOT NULL,
      content TEXT NOT NULL,
      summary TEXT,
      status TEXT DEFAULT 'draft',
      source_artifact_id INTEGER,
      metadata TEXT DEFAULT '{}',
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );
-- ai_traces
CREATE TABLE IF NOT EXISTS ai_traces (
      id TEXT PRIMARY KEY,
      trace_id TEXT NOT NULL,
      parent_span_id TEXT,
      name TEXT NOT NULL,
      type TEXT NOT NULL DEFAULT 'span',
      model TEXT,
      input TEXT,
      output TEXT,
      input_tokens INTEGER,
      output_tokens INTEGER,
      total_tokens INTEGER,
      latency_ms INTEGER,
      cost_usd DOUBLE PRECISION,
      status TEXT NOT NULL DEFAULT 'running',
      error_message TEXT,
      metadata TEXT,
      started_at TEXT NOT NULL,
      ended_at TEXT,
      created_at TEXT DEFAULT (CURRENT_TIMESTAMP)
    , endpoint TEXT, conversation_id INTEGER);
-- artemis_application_artifacts
CREATE TABLE IF NOT EXISTS artemis_application_artifacts (
      id BIGSERIAL PRIMARY KEY,
      application_id INTEGER NOT NULL,
      artifact_type TEXT NOT NULL,
      document_id INTEGER NULL,
      media_asset_id INTEGER NULL,
      label TEXT,
      sent_at TEXT,
      notes TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
      CHECK (document_id IS NOT NULL OR media_asset_id IS NOT NULL)
    );
-- artemis_applications
CREATE TABLE IF NOT EXISTS artemis_applications (
      id BIGSERIAL PRIMARY KEY,
      position_id INTEGER NOT NULL,
      status TEXT NOT NULL DEFAULT 'saved',
      priority TEXT DEFAULT 'medium',
      fit_score INTEGER,
      applied_at TEXT,
      deadline_at TEXT,
      follow_up_at TEXT,
      last_activity_at TEXT,
      source TEXT,
      contact_name TEXT,
      contact_email TEXT,
      notes TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );
-- artemis_communications
CREATE TABLE IF NOT EXISTS artemis_communications (
      id BIGSERIAL PRIMARY KEY,
      application_id INTEGER NULL,
      company_id INTEGER NULL,
      position_id INTEGER NULL,
      channel TEXT NOT NULL DEFAULT 'note',
      direction TEXT NOT NULL DEFAULT 'internal_note',
      contact_name TEXT,
      contact_email TEXT,
      subject TEXT,
      raw_text TEXT,
      summary TEXT,
      occurred_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      next_action TEXT,
      next_action_due_at TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );
-- artemis_companies
CREATE TABLE IF NOT EXISTS artemis_companies (
      id BIGSERIAL PRIMARY KEY,
      name TEXT NOT NULL,
      website TEXT,
      industry TEXT,
      size TEXT,
      headquarters TEXT,
      location TEXT,
      linkedin_url TEXT,
      description TEXT,
      notes TEXT,
      tags TEXT DEFAULT '[]',
      summary TEXT,
      summary_updated_at TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );
-- artemis_job_positions
CREATE TABLE IF NOT EXISTS artemis_job_positions (
      id BIGSERIAL PRIMARY KEY,
      company_id INTEGER NOT NULL,
      title TEXT NOT NULL,
      department TEXT,
      employment_type TEXT,
      seniority TEXT,
      location TEXT,
      work_mode TEXT DEFAULT 'unknown',
      source_url TEXT,
      source_platform TEXT,
      salary_min INTEGER,
      salary_max INTEGER,
      salary_currency TEXT,
      benefits TEXT DEFAULT '[]',
      responsibilities TEXT DEFAULT '[]',
      requirements TEXT DEFAULT '[]',
      nice_to_have TEXT DEFAULT '[]',
      raw_posting_text TEXT,
      extracted_data TEXT DEFAULT '{}',
      summary TEXT,
      summary_updated_at TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );
-- artemis_tasks
CREATE TABLE IF NOT EXISTS artemis_tasks (
      id BIGSERIAL PRIMARY KEY,
      application_id INTEGER,
      title TEXT NOT NULL,
      description TEXT,
      due_at TEXT,
      status TEXT NOT NULL DEFAULT 'open',
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      completed_at TEXT,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );
-- athena_learning_items
CREATE TABLE IF NOT EXISTS athena_learning_items (
      id BIGSERIAL PRIMARY KEY,
      user_id TEXT DEFAULT 'default',

      -- Item identification
      type TEXT NOT NULL CHECK(type IN ('flashcard', 'quiz_question', 'concept')),
      repository TEXT NOT NULL,
      commit_hash TEXT,

      -- Content (JSON structure depends on type)
      content TEXT NOT NULL,

      -- FSRS spaced repetition fields
      difficulty DOUBLE PRECISION DEFAULT 0,
      stability DOUBLE PRECISION DEFAULT 0,
      retrievability DOUBLE PRECISION DEFAULT 1,
      last_review TEXT,
      next_review TEXT,
      review_count INTEGER DEFAULT 0,
      correct_count INTEGER DEFAULT 0,

      -- Metadata
      tags TEXT DEFAULT '[]',
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );
-- athena_sessions
CREATE TABLE IF NOT EXISTS athena_sessions (
      id BIGSERIAL PRIMARY KEY,
      user_id TEXT DEFAULT 'default',

      -- Session info
      repository TEXT NOT NULL,
      session_type TEXT NOT NULL CHECK(session_type IN ('lesson', 'quiz', 'review')),

      -- Generated content (JSON)
      content TEXT NOT NULL,

      -- Results (for quizzes)
      score INTEGER,
      total_questions INTEGER,
      answers TEXT, -- JSON array of user answers

      -- Timing
      started_at TEXT DEFAULT CURRENT_TIMESTAMP,
      completed_at TEXT
    );
-- atropos_corrections
CREATE TABLE IF NOT EXISTS atropos_corrections (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'default',
  original_text TEXT NOT NULL,
  corrected_text TEXT NOT NULL,
  had_changes INTEGER DEFAULT 0,
  intent_questions TEXT DEFAULT '[]',
  source_context TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
-- atropos_dictionary
CREATE TABLE IF NOT EXISTS atropos_dictionary (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'default',
  term TEXT NOT NULL,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);
-- atropos_memories
CREATE TABLE IF NOT EXISTS atropos_memories (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'default',
  content TEXT NOT NULL,
  tags TEXT DEFAULT '[]',
  frequency INTEGER DEFAULT 1,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);
-- atropos_stats
CREATE TABLE IF NOT EXISTS atropos_stats (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'default',
  total_checks INTEGER DEFAULT 0,
  total_corrections INTEGER DEFAULT 0,
  total_characters_corrected INTEGER DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);
-- chat_conversations
CREATE TABLE IF NOT EXISTS chat_conversations (
      id BIGSERIAL PRIMARY KEY,
      title TEXT NOT NULL,
      messages TEXT NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    , summary TEXT, summary_updated_at TEXT, tags TEXT DEFAULT '[]', importance INTEGER DEFAULT 0, message_count INTEGER DEFAULT 0, estimated_tokens INTEGER DEFAULT 0, session_config TEXT, artifact_refs TEXT DEFAULT '[]', chat_log TEXT DEFAULT '[]', cost_usd DOUBLE PRECISION DEFAULT 0, actual_input_tokens INTEGER DEFAULT 0, actual_output_tokens INTEGER DEFAULT 0);
-- client_errors
CREATE TABLE IF NOT EXISTS client_errors (
  id BIGSERIAL PRIMARY KEY,
  session_id TEXT NOT NULL,
  received_at TEXT NOT NULL,
  kind TEXT NOT NULL,
  message TEXT NOT NULL,
  stack TEXT,
  source TEXT,
  lineno INTEGER,
  colno INTEGER,
  url TEXT,
  user_agent TEXT,
  conversation_id INTEGER,
  context_json TEXT,
  mem_tail_json TEXT
);
-- client_memlog
CREATE TABLE IF NOT EXISTS client_memlog (
      id BIGSERIAL PRIMARY KEY,
      session_id TEXT NOT NULL,
      received_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
      reason TEXT NOT NULL,
      trigger TEXT NOT NULL,
      user_agent TEXT,
      url TEXT,
      conversation_id INTEGER,
      sample_count INTEGER NOT NULL DEFAULT 0,
      peak_heap_mb INTEGER,
      peak_nodes INTEGER,
      samples_json TEXT NOT NULL
    );
-- document_types
CREATE TABLE IF NOT EXISTS document_types (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      description TEXT NOT NULL DEFAULT '',
      color TEXT NOT NULL DEFAULT 'emerald',
      icon TEXT NOT NULL DEFAULT 'file-text',
      sortOrder INTEGER NOT NULL DEFAULT 0
    );