-- FORTRESS-001: Postgres mirror of Tartarus SQLite vault
-- Generated by web/scripts/fortress-sqlite-to-pg.mjs — do not hand-edit; regenerate instead
-- Source: /Users/guillermo.as/Documents/Software/Laboratory/tartarus/data/journal.db
-- Generated: 2026-07-01T10:11:24.344Z

CREATE TABLE IF NOT EXISTS fortress_sync_meta (
  id BIGSERIAL PRIMARY KEY,
  table_name TEXT NOT NULL UNIQUE,
  sqlite_row_count INTEGER,
  pushed_row_count INTEGER,
  last_pushed_at TIMESTAMPTZ DEFAULT NOW(),
  checksum TEXT
);

-- ai_artifacts
CREATE TABLE IF NOT EXISTS ai_artifacts (
      id BIGSERIAL PRIMARY KEY,
      integration_key TEXT NOT NULL,
      kind TEXT NOT NULL,
      source_path TEXT NOT NULL,
      title TEXT NOT NULL,
      summary TEXT,
      content TEXT,
      metadata TEXT DEFAULT '{}',
      content_hash TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(integration_key, kind, source_path)
    );

-- ai_integrations
CREATE TABLE IF NOT EXISTS ai_integrations (
      key TEXT PRIMARY KEY,
      display_name TEXT NOT NULL,
      status TEXT NOT NULL,
      version TEXT,
      auth_status TEXT,
      source_paths TEXT DEFAULT '[]',
      config_summary TEXT,
      metadata TEXT DEFAULT '{}',
      last_scanned_at TEXT
    );

-- ai_log_events
CREATE TABLE IF NOT EXISTS ai_log_events (
      id BIGSERIAL PRIMARY KEY,
      session_id INTEGER NOT NULL,
      sequence INTEGER NOT NULL,
      timestamp TEXT,
      actor TEXT NOT NULL,
      event_type TEXT NOT NULL,
      text TEXT NOT NULL,
      tooling TEXT,
      params TEXT DEFAULT '{}',
      source_event_type TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (session_id) REFERENCES ai_log_sessions(id) ON DELETE CASCADE,
      UNIQUE(session_id, sequence)
    );

-- ai_log_sessions
CREATE TABLE IF NOT EXISTS ai_log_sessions (
      id BIGSERIAL PRIMARY KEY,
      integration_key TEXT NOT NULL,
      stable_id TEXT NOT NULL,
      source_path TEXT NOT NULL,
      title TEXT NOT NULL,
      summary TEXT,
      started_at TEXT,
      updated_at TEXT,
      message_count INTEGER DEFAULT 0,
      metadata TEXT DEFAULT '{}',
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(integration_key, stable_id, source_path)
    );

-- ai_prompt_active
CREATE TABLE IF NOT EXISTS ai_prompt_active (
      prompt_slug TEXT PRIMARY KEY,
      version     INTEGER NOT NULL,
      updated_at  TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

-- ai_prompt_versions
CREATE TABLE IF NOT EXISTS ai_prompt_versions (
      id          BIGSERIAL PRIMARY KEY,
      prompt_slug TEXT    NOT NULL,
      version     INTEGER NOT NULL,
      content     TEXT    NOT NULL,
      config      TEXT    NOT NULL DEFAULT '{}',
      label       TEXT    NOT NULL DEFAULT 'draft',
      created_at  TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP),
      created_by  TEXT    NOT NULL DEFAULT 'system',
      UNIQUE(prompt_slug, version)
    );

-- ai_proposals
CREATE TABLE IF NOT EXISTS ai_proposals (
      id BIGSERIAL PRIMARY KEY,
      integration_key TEXT NOT NULL,
      target_kind TEXT NOT NULL,
      target_path TEXT NOT NULL,
      title TEXT NOT NULL,
      content TEXT NOT NULL,
      summary TEXT,
      status TEXT DEFAULT 'draft',
      source_artifact_id INTEGER,
      metadata TEXT DEFAULT '{}',
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );

-- ai_traces
CREATE TABLE IF NOT EXISTS ai_traces (
      id TEXT PRIMARY KEY,
      trace_id TEXT NOT NULL,
      parent_span_id TEXT,
      name TEXT NOT NULL,
      type TEXT NOT NULL DEFAULT 'span',
      model TEXT,
      input TEXT,
      output TEXT,
      input_tokens INTEGER,
      output_tokens INTEGER,
      total_tokens INTEGER,
      latency_ms INTEGER,
      cost_usd DOUBLE PRECISION,
      status TEXT NOT NULL DEFAULT 'running',
      error_message TEXT,
      metadata TEXT,
      started_at TEXT NOT NULL,
      ended_at TEXT,
      created_at TEXT DEFAULT (CURRENT_TIMESTAMP)
    , endpoint TEXT, conversation_id INTEGER);

-- artemis_application_artifacts
CREATE TABLE IF NOT EXISTS artemis_application_artifacts (
      id BIGSERIAL PRIMARY KEY,
      application_id INTEGER NOT NULL REFERENCES artemis_applications(id) ON DELETE CASCADE,
      artifact_type TEXT NOT NULL,
      document_id INTEGER REFERENCES documents(id) ON DELETE SET NULL,
      media_asset_id INTEGER REFERENCES media_assets(id) ON DELETE SET NULL,
      label TEXT,
      sent_at TEXT,
      notes TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
      CHECK (document_id IS NOT NULL OR media_asset_id IS NOT NULL)
    );

-- artemis_applications
CREATE TABLE IF NOT EXISTS artemis_applications (
      id BIGSERIAL PRIMARY KEY,
      position_id INTEGER NOT NULL REFERENCES artemis_job_positions(id) ON DELETE CASCADE,
      status TEXT NOT NULL DEFAULT 'saved',
      priority TEXT DEFAULT 'medium',
      fit_score INTEGER,
      applied_at TEXT,
      deadline_at TEXT,
      follow_up_at TEXT,
      last_activity_at TEXT,
      source TEXT,
      contact_name TEXT,
      contact_email TEXT,
      notes TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );

-- artemis_communications
CREATE TABLE IF NOT EXISTS artemis_communications (
      id BIGSERIAL PRIMARY KEY,
      application_id INTEGER REFERENCES artemis_applications(id) ON DELETE SET NULL,
      company_id INTEGER REFERENCES artemis_companies(id) ON DELETE SET NULL,
      position_id INTEGER REFERENCES artemis_job_positions(id) ON DELETE SET NULL,
      channel TEXT NOT NULL DEFAULT 'note',
      direction TEXT NOT NULL DEFAULT 'internal_note',
      contact_name TEXT,
      contact_email TEXT,
      subject TEXT,
      raw_text TEXT,
      summary TEXT,
      occurred_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
      next_action TEXT,
      next_action_due_at TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );

-- artemis_companies
CREATE TABLE IF NOT EXISTS artemis_companies (
      id BIGSERIAL PRIMARY KEY,
      name TEXT NOT NULL,
      website TEXT,
      industry TEXT,
      size TEXT,
      headquarters TEXT,
      location TEXT,
      linkedin_url TEXT,
      description TEXT,
      notes TEXT,
      tags TEXT DEFAULT '[]',
      summary TEXT,
      summary_updated_at TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );

-- artemis_job_positions
CREATE TABLE IF NOT EXISTS artemis_job_positions (
      id BIGSERIAL PRIMARY KEY,
      company_id INTEGER NOT NULL REFERENCES artemis_companies(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      department TEXT,
      employment_type TEXT,
      seniority TEXT,
      location TEXT,
      work_mode TEXT DEFAULT 'unknown',
      source_url TEXT,
      source_platform TEXT,
      salary_min INTEGER,
      salary_max INTEGER,
      salary_currency TEXT,
      benefits TEXT DEFAULT '[]',
      responsibilities TEXT DEFAULT '[]',
      requirements TEXT DEFAULT '[]',
      nice_to_have TEXT DEFAULT '[]',
      raw_posting_text TEXT,
      extracted_data TEXT DEFAULT '{}',
      summary TEXT,
      summary_updated_at TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );

-- artemis_tasks
CREATE TABLE IF NOT EXISTS artemis_tasks (
      id BIGSERIAL PRIMARY KEY,
      application_id INTEGER REFERENCES artemis_applications(id) ON DELETE CASCADE,
      title TEXT NOT NULL,
      description TEXT,
      due_at TEXT,
      status TEXT NOT NULL DEFAULT 'open',
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      completed_at TEXT,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );

-- athena_learning_items
CREATE TABLE IF NOT EXISTS athena_learning_items (
      id BIGSERIAL PRIMARY KEY,
      user_id TEXT DEFAULT 'default',

      -- Item identification
      type TEXT NOT NULL CHECK(type IN ('flashcard', 'quiz_question', 'concept')),
      repository TEXT NOT NULL,
      commit_hash TEXT,

      -- Content (JSON structure depends on type)
      content TEXT NOT NULL,

      -- FSRS spaced repetition fields
      difficulty DOUBLE PRECISION DEFAULT 0,
      stability DOUBLE PRECISION DEFAULT 0,
      retrievability DOUBLE PRECISION DEFAULT 1,
      last_review TEXT,
      next_review TEXT,
      review_count INTEGER DEFAULT 0,
      correct_count INTEGER DEFAULT 0,

      -- Metadata
      tags TEXT DEFAULT '[]',
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );

-- athena_sessions
CREATE TABLE IF NOT EXISTS athena_sessions (
      id BIGSERIAL PRIMARY KEY,
      user_id TEXT DEFAULT 'default',

      -- Session info
      repository TEXT NOT NULL,
      session_type TEXT NOT NULL CHECK(session_type IN ('lesson', 'quiz', 'review')),

      -- Generated content (JSON)
      content TEXT NOT NULL,

      -- Results (for quizzes)
      score INTEGER,
      total_questions INTEGER,
      answers TEXT, -- JSON array of user answers

      -- Timing
      started_at TEXT DEFAULT CURRENT_TIMESTAMP,
      completed_at TEXT
    );

-- atropos_corrections
CREATE TABLE IF NOT EXISTS atropos_corrections (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'default',
  original_text TEXT NOT NULL,
  corrected_text TEXT NOT NULL,
  had_changes INTEGER DEFAULT 0,
  intent_questions TEXT DEFAULT '[]',
  source_context TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- atropos_dictionary
CREATE TABLE IF NOT EXISTS atropos_dictionary (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'default',
  term TEXT NOT NULL,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- atropos_memories
CREATE TABLE IF NOT EXISTS atropos_memories (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'default',
  content TEXT NOT NULL,
  tags TEXT DEFAULT '[]',
  frequency INTEGER DEFAULT 1,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- atropos_stats
CREATE TABLE IF NOT EXISTS atropos_stats (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'default',
  total_checks INTEGER DEFAULT 0,
  total_corrections INTEGER DEFAULT 0,
  total_characters_corrected INTEGER DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- chat_conversations
CREATE TABLE IF NOT EXISTS chat_conversations (
      id BIGSERIAL PRIMARY KEY,
      title TEXT NOT NULL,
      messages TEXT NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    , summary TEXT, summary_updated_at TEXT, tags TEXT DEFAULT '[]', importance INTEGER DEFAULT 0, message_count INTEGER DEFAULT 0, estimated_tokens INTEGER DEFAULT 0, session_config TEXT, artifact_refs TEXT DEFAULT '[]', chat_log TEXT DEFAULT '[]', cost_usd DOUBLE PRECISION DEFAULT 0, actual_input_tokens INTEGER DEFAULT 0, actual_output_tokens INTEGER DEFAULT 0);

-- client_errors
CREATE TABLE IF NOT EXISTS client_errors (
  id BIGSERIAL PRIMARY KEY,
  session_id TEXT NOT NULL,
  received_at TEXT NOT NULL,
  kind TEXT NOT NULL,
  message TEXT NOT NULL,
  stack TEXT,
  source TEXT,
  lineno INTEGER,
  colno INTEGER,
  url TEXT,
  user_agent TEXT,
  conversation_id INTEGER,
  context_json TEXT,
  mem_tail_json TEXT
);

-- client_memlog
CREATE TABLE IF NOT EXISTS client_memlog (
      id BIGSERIAL PRIMARY KEY,
      session_id TEXT NOT NULL,
      received_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
      reason TEXT NOT NULL,
      trigger TEXT NOT NULL,
      user_agent TEXT,
      url TEXT,
      conversation_id INTEGER,
      sample_count INTEGER NOT NULL DEFAULT 0,
      peak_heap_mb INTEGER,
      peak_nodes INTEGER,
      samples_json TEXT NOT NULL
    );

-- document_types
CREATE TABLE IF NOT EXISTS document_types (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      description TEXT NOT NULL DEFAULT '',
      color TEXT NOT NULL DEFAULT 'emerald',
      icon TEXT NOT NULL DEFAULT 'file-text',
      sortOrder INTEGER NOT NULL DEFAULT 0
    );

-- documents
CREATE TABLE IF NOT EXISTS documents (
      id BIGSERIAL PRIMARY KEY,
      slug TEXT UNIQUE NOT NULL,
      type TEXT NOT NULL CHECK(type IN ('writing', 'prompt', 'note')),
      title TEXT NOT NULL,
      content TEXT NOT NULL,
      language TEXT DEFAULT 'en',
      metadata TEXT DEFAULT '{}',
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    , summary TEXT, summary_updated_at TEXT);

-- education
CREATE TABLE IF NOT EXISTS education (
      id TEXT PRIMARY KEY,
      degree TEXT NOT NULL,
      field TEXT NOT NULL,
      institution TEXT NOT NULL,
      location TEXT NOT NULL,
      dateStart TEXT NOT NULL,
      dateEnd TEXT NOT NULL,
      tagline TEXT NOT NULL,
      note TEXT,
      focusAreas TEXT DEFAULT '[]',
      achievements TEXT DEFAULT '[]'
    , logo TEXT, summary TEXT, summary_updated_at TEXT);

-- entry_attachments
CREATE TABLE IF NOT EXISTS entry_attachments (
      id BIGSERIAL PRIMARY KEY,
      commit_hash TEXT NOT NULL,
      filename TEXT NOT NULL,
      mime_type TEXT NOT NULL,
      data BYTEA,
      file_size INTEGER NOT NULL,
      uploaded_at TEXT DEFAULT CURRENT_TIMESTAMP, description TEXT, summary TEXT,
      FOREIGN KEY (commit_hash) REFERENCES journal_entries(commit_hash) ON DELETE CASCADE
    , object_key TEXT
);

-- hermes_dictionary
CREATE TABLE IF NOT EXISTS hermes_dictionary (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'default',
  term TEXT NOT NULL,
  preserve_as TEXT,
  source_language TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- hermes_memories
CREATE TABLE IF NOT EXISTS hermes_memories (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'default',
  content TEXT NOT NULL,
  source_language TEXT,
  target_language TEXT,
  tags TEXT DEFAULT '[]',
  frequency INTEGER DEFAULT 1,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- hermes_stats
CREATE TABLE IF NOT EXISTS hermes_stats (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'default',
  total_translations INTEGER DEFAULT 0,
  total_characters_translated INTEGER DEFAULT 0,
  language_pairs_used TEXT DEFAULT '{}',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- hermes_translations
CREATE TABLE IF NOT EXISTS hermes_translations (
  id BIGSERIAL PRIMARY KEY,
  user_id TEXT NOT NULL DEFAULT 'default',
  original_text TEXT NOT NULL,
  translated_text TEXT NOT NULL,
  source_language TEXT NOT NULL,
  target_language TEXT NOT NULL,
  tone TEXT NOT NULL DEFAULT 'neutral' CHECK(tone IN ('formal', 'neutral', 'slang')),
  had_changes INTEGER DEFAULT 1,
  clarification_questions TEXT DEFAULT '[]',
  source_context TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- journal_entries
CREATE TABLE IF NOT EXISTS journal_entries (
      id BIGSERIAL PRIMARY KEY,
      commit_hash TEXT UNIQUE NOT NULL,
      repository TEXT NOT NULL,
      branch TEXT NOT NULL,
      author TEXT NOT NULL,
      date TEXT NOT NULL,
      why TEXT NOT NULL,
      what_changed TEXT NOT NULL,
      decisions TEXT NOT NULL,
      technologies TEXT NOT NULL,
      kronus_wisdom TEXT,
      raw_agent_report TEXT NOT NULL,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP
    , code_author TEXT, team_members TEXT DEFAULT '[]', files_changed TEXT, summary TEXT, summary_updated_at TEXT);

-- kronus_context_metrics_cache
CREATE TABLE IF NOT EXISTS kronus_context_metrics_cache (
      id INTEGER PRIMARY KEY CHECK (id = 1),
      payload_json TEXT NOT NULL,
      computed_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP),
      stale INTEGER NOT NULL DEFAULT 1
    );

-- kronus_context_metrics_meta
CREATE TABLE IF NOT EXISTS kronus_context_metrics_meta (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  stale INTEGER NOT NULL DEFAULT 1,
  computed_at TEXT
);

-- kronus_context_section_metrics
CREATE TABLE IF NOT EXISTS kronus_context_section_metrics (
  section_key TEXT PRIMARY KEY REFERENCES kronus_context_sections(section_key),
  item_count INTEGER NOT NULL DEFAULT 0,
  token_estimate INTEGER NOT NULL DEFAULT 0,
  breakdown_json TEXT NOT NULL DEFAULT '{}',
  computed_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP)
);

-- kronus_context_sections
CREATE TABLE IF NOT EXISTS kronus_context_sections (
  section_key TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'soul',
  soul_config_key TEXT,
  source_tables TEXT NOT NULL DEFAULT '[]',
  sort_order INTEGER NOT NULL DEFAULT 0
);

-- linear_issues
CREATE TABLE IF NOT EXISTS linear_issues (
        id TEXT PRIMARY KEY,
        identifier TEXT NOT NULL,
        title TEXT NOT NULL,
        description TEXT,
        url TEXT NOT NULL,
        priority INTEGER,
        state_id TEXT,
        state_name TEXT,
        assignee_id TEXT,
        assignee_name TEXT,
        team_id TEXT,
        team_name TEXT,
        team_key TEXT,
        project_id TEXT,
        project_name TEXT,
        parent_id TEXT,
        synced_at TEXT DEFAULT CURRENT_TIMESTAMP,
        deleted_at TEXT,
        is_deleted INTEGER DEFAULT 0,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP
      , summary TEXT, summary_updated_at TEXT);

-- linear_project_updates
CREATE TABLE IF NOT EXISTS linear_project_updates (
  id TEXT PRIMARY KEY,
  project_id TEXT NOT NULL,
  project_name TEXT,
  body TEXT NOT NULL,
  health TEXT, -- "onTrack" | "atRisk" | "offTrack"
  user_id TEXT,
  user_name TEXT,
  synced_at TEXT DEFAULT CURRENT_TIMESTAMP,
  is_deleted INTEGER DEFAULT 0,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- linear_projects
CREATE TABLE IF NOT EXISTS linear_projects (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT,
        content TEXT,
        state TEXT,
        progress DOUBLE PRECISION,
        target_date TEXT,
        start_date TEXT,
        url TEXT NOT NULL,
        lead_id TEXT,
        lead_name TEXT,
        team_ids TEXT DEFAULT '[]',
        member_ids TEXT DEFAULT '[]',
        synced_at TEXT DEFAULT CURRENT_TIMESTAMP,
        deleted_at TEXT,
        is_deleted INTEGER DEFAULT 0,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP
      , summary TEXT, summary_updated_at TEXT);

-- media_assets
CREATE TABLE IF NOT EXISTS media_assets (
      id BIGSERIAL PRIMARY KEY,
      filename TEXT NOT NULL,
      mime_type TEXT NOT NULL,
      data TEXT,
      file_size INTEGER NOT NULL,
      description TEXT,
      prompt TEXT,
      model TEXT,
      tags TEXT DEFAULT '[]',
      destination TEXT NOT NULL CHECK(destination IN ('journal', 'repository', 'media')),
      commit_hash TEXT,
      document_id INTEGER,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP, alt TEXT, drive_url TEXT, supabase_url TEXT, portfolio_project_id TEXT REFERENCES portfolio_projects(id) ON DELETE SET NULL, width INTEGER, height INTEGER, label TEXT,
      FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE SET NULL
    , object_key TEXT
);

-- media_digests
CREATE TABLE IF NOT EXISTS media_digests (
      id BIGSERIAL PRIMARY KEY,
      digest_date TEXT NOT NULL UNIQUE,
      title TEXT,
      summary TEXT,
      commentary TEXT,
      sections TEXT DEFAULT '[]',
      inbox_summary TEXT,
      item_count INTEGER DEFAULT 0,
      model TEXT,
      status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'complete', 'failed')),
      document_slug TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );

-- muse_config
CREATE TABLE IF NOT EXISTS muse_config (
      id                  INTEGER PRIMARY KEY CHECK (id = 1),
      provider            TEXT    NOT NULL DEFAULT 'openai',
      driver_model        TEXT    NOT NULL DEFAULT 'gpt-5.4',
      painter_model       TEXT    NOT NULL DEFAULT 'gpt-image-2',
      observe_model       TEXT    NOT NULL DEFAULT 'gemini-2.5-flash',
      tick_every          INTEGER NOT NULL DEFAULT 3,
      mood_size           TEXT    NOT NULL DEFAULT '1K',
      infographic_size    TEXT    NOT NULL DEFAULT '2K',
      mood_quality        TEXT    NOT NULL DEFAULT 'low',
      infographic_quality TEXT    NOT NULL DEFAULT 'high',
      updated_at          TEXT    NOT NULL DEFAULT (CURRENT_TIMESTAMP)
    );

-- notion_pages
CREATE TABLE IF NOT EXISTS notion_pages (
        id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        content TEXT,
        parent_id TEXT,
        parent_type TEXT,
        url TEXT,
        created_by TEXT,
        created_by_name TEXT,
        last_edited_by TEXT,
        last_edited_by_name TEXT,
        icon TEXT,
        cover_url TEXT,
        archived INTEGER DEFAULT 0,
        summary TEXT,
        synced_at TEXT DEFAULT CURRENT_TIMESTAMP,
        deleted_at TEXT,
        is_deleted INTEGER DEFAULT 0,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
        last_edited_at TEXT
      , summary_updated_at TEXT);

-- portfolio_products
CREATE TABLE IF NOT EXISTS portfolio_products (
        id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        tagline TEXT NOT NULL,
        humane_description TEXT NOT NULL,
        buyer_pain TEXT NOT NULL,
        promise TEXT NOT NULL,
        deliverables TEXT DEFAULT '[]',
        starting_price TEXT NOT NULL,
        timeline TEXT NOT NULL,
        cta_label TEXT NOT NULL,
        accent TEXT NOT NULL DEFAULT 'gold' CHECK (accent IN ('gold', 'red', 'blue')),
        wildcard INTEGER DEFAULT 0,
        display_order INTEGER DEFAULT 0,
        summary TEXT,
        summary_updated_at TEXT,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP
      , blueprint_title TEXT, service_tiers TEXT DEFAULT '[]', case_study_cta_label TEXT);

-- portfolio_projects
CREATE TABLE IF NOT EXISTS portfolio_projects (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    company TEXT,
    date_completed TEXT,
    status TEXT NOT NULL DEFAULT 'shipped' CHECK (status IN ('shipped', 'wip', 'archived')),
    featured INTEGER DEFAULT 0,
    image TEXT,
    excerpt TEXT,
    description TEXT,
    role TEXT,
    technologies TEXT DEFAULT '[]',
    metrics TEXT DEFAULT '{}',
    links TEXT DEFAULT '{}',
    tags TEXT DEFAULT '[]',
    sort_order INTEGER DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
, summary TEXT, summary_updated_at TEXT, product_ids TEXT DEFAULT '[]', visible INTEGER DEFAULT 1, diagram_image TEXT, image_fallback TEXT, case_study_level TEXT, humane_problem TEXT, humane_solution TEXT, technical_problem TEXT, technical_solution TEXT, technical_specs TEXT);

-- prompt_entry_links
CREATE TABLE IF NOT EXISTS prompt_entry_links (
  id BIGSERIAL PRIMARY KEY,
  prompt_id INTEGER NOT NULL REFERENCES prompts(id) ON DELETE CASCADE,
  commit_hash TEXT NOT NULL,
  link_type TEXT NOT NULL DEFAULT 'reference' CHECK(link_type IN ('reference', 'used_by', 'created_for')),
  notes TEXT,
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(prompt_id, commit_hash, link_type)
);

-- prompt_projects
CREATE TABLE IF NOT EXISTS prompt_projects (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'archived', 'draft')),
  tags TEXT DEFAULT '[]',
  metadata TEXT DEFAULT '{}',
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- prompt_trace_links
CREATE TABLE IF NOT EXISTS prompt_trace_links (
  id BIGSERIAL PRIMARY KEY,
  prompt_id INTEGER NOT NULL REFERENCES prompts(id) ON DELETE CASCADE,
  trace_id TEXT NOT NULL,
  prompt_version INTEGER NOT NULL,
  -- Performance metrics (copied from trace for quick access)
  input_tokens INTEGER,
  output_tokens INTEGER,
  latency_ms INTEGER,
  cost_usd DOUBLE PRECISION,
  status TEXT,
  -- Timestamps
  created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- prompts
CREATE TABLE IF NOT EXISTS prompts (
  id BIGSERIAL PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  project_id TEXT REFERENCES prompt_projects(id) ON DELETE SET NULL,
  -- Core content
  name TEXT NOT NULL,
  content TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'system' CHECK(role IN ('system', 'user', 'assistant', 'chat')),
  -- Prompt metadata
  purpose TEXT,
  input_schema TEXT,
  output_schema TEXT,
  config TEXT,
  -- Versioning
  version INTEGER NOT NULL DEFAULT 1,
  is_latest INTEGER NOT NULL DEFAULT 1,
  parent_version_id INTEGER REFERENCES prompts(id) ON DELETE SET NULL,
  -- Status
  status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'draft', 'deprecated', 'archived')),
  -- Classification
  tags TEXT DEFAULT '[]',
  language TEXT DEFAULT 'en',
  -- AI summary for Kronus indexing
  summary TEXT,
  -- Legacy document link (for migration)
  legacy_document_id INTEGER,
  -- Timestamps
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- public_media
CREATE TABLE IF NOT EXISTS public_media (
      id BIGSERIAL PRIMARY KEY,
      digest_id INTEGER REFERENCES media_digests(id) ON DELETE CASCADE,
      url TEXT,
      title TEXT NOT NULL,
      snippet TEXT,
      publication TEXT,
      author TEXT,
      topic TEXT,
      topic_label TEXT,
      perspective TEXT DEFAULT 'unknown'
        CHECK (perspective IN ('left', 'right', 'state', 'sensationalist', 'neutral', 'unknown')),
      importance INTEGER DEFAULT 0,
      language TEXT DEFAULT 'en',
      published_at TEXT,
      source_query TEXT,
      provider TEXT,
      metadata TEXT DEFAULT '{}',
      created_at TEXT DEFAULT CURRENT_TIMESTAMP
    );

-- repository_overviews
CREATE TABLE IF NOT EXISTS "repository_overviews" (
          id BIGSERIAL PRIMARY KEY,
          repository TEXT UNIQUE NOT NULL,
          git_url TEXT,
          summary TEXT,
          purpose TEXT,
          architecture TEXT,
          key_decisions TEXT,
          technologies TEXT,
          status TEXT,
          linear_project_id TEXT,
          linear_issue_id TEXT,
          updated_at TEXT DEFAULT CURRENT_TIMESTAMP
        , file_structure TEXT, tech_stack TEXT, frontend TEXT, backend TEXT, database_info TEXT, services TEXT, custom_tooling TEXT, data_flow TEXT, patterns TEXT, commands TEXT, extended_notes TEXT, last_synced_entry TEXT, entries_synced INTEGER, schema_version INTEGER DEFAULT 1, sections_json TEXT, last_scanned_commit TEXT, total_updates INTEGER DEFAULT 0, summary_updated_at TEXT);

-- skill_categories
CREATE TABLE IF NOT EXISTS skill_categories (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      color TEXT NOT NULL DEFAULT 'gray',
      icon TEXT NOT NULL DEFAULT 'tag',
      sortOrder INTEGER NOT NULL DEFAULT 0
    );

-- skills
CREATE TABLE IF NOT EXISTS skills (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      category TEXT NOT NULL,
      magnitude INTEGER NOT NULL CHECK(magnitude >= 1 AND magnitude <= 4),
      description TEXT NOT NULL,
      icon TEXT,
      color TEXT,
      url TEXT,
      tags TEXT DEFAULT '[]',
      firstUsed TEXT,
      lastUsed TEXT
    , summary TEXT, summary_updated_at TEXT);

-- slack_conversation_summary_runs
CREATE TABLE IF NOT EXISTS slack_conversation_summary_runs (
      id BIGSERIAL PRIMARY KEY,
      conversation_id TEXT NOT NULL,
      model TEXT NOT NULL,
      message_count INTEGER NOT NULL DEFAULT 0,
      status TEXT NOT NULL,
      error TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP
    );

-- slack_conversations
CREATE TABLE IF NOT EXISTS slack_conversations (
      id TEXT PRIMARY KEY,
      team_id TEXT,
      name TEXT,
      type TEXT NOT NULL,
      vault_type TEXT NOT NULL,
      is_member INTEGER DEFAULT 0,
      is_archived INTEGER DEFAULT 0,
      is_private INTEGER DEFAULT 0,
      is_im INTEGER DEFAULT 0,
      is_mpim INTEGER DEFAULT 0,
      is_channel INTEGER DEFAULT 0,
      user_id TEXT,
      topic TEXT,
      purpose TEXT,
      num_members INTEGER,
      raw_json TEXT NOT NULL,
      summary TEXT,
      summarized_at TEXT,
      latest_ts TEXT,
      oldest_ts TEXT,
      synced_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );

-- slack_messages
CREATE TABLE IF NOT EXISTS slack_messages (
      id TEXT PRIMARY KEY,
      conversation_id TEXT NOT NULL,
      ts TEXT NOT NULL,
      user_id TEXT,
      username TEXT,
      bot_id TEXT,
      subtype TEXT,
      text TEXT,
      thread_ts TEXT,
      parent_user_id TEXT,
      reply_count INTEGER,
      is_thread_parent INTEGER DEFAULT 0,
      raw_json TEXT NOT NULL,
      summary TEXT,
      summarized_at TEXT,
      synced_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (conversation_id) REFERENCES slack_conversations(id) ON DELETE CASCADE
    );

-- slack_sync_state
CREATE TABLE IF NOT EXISTS slack_sync_state (
      scope TEXT PRIMARY KEY,
      cursor TEXT,
      last_synced_ts TEXT,
      stats_json TEXT DEFAULT '{}',
      last_error TEXT,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );

-- slack_users
CREATE TABLE IF NOT EXISTS slack_users (
      id TEXT PRIMARY KEY,
      team_id TEXT,
      name TEXT,
      real_name TEXT,
      tz TEXT,
      is_bot INTEGER DEFAULT 0,
      deleted INTEGER DEFAULT 0,
      profile_json TEXT DEFAULT '{}',
      raw_json TEXT NOT NULL,
      synced_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    );

-- slite_notes
CREATE TABLE IF NOT EXISTS slite_notes (
        id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        content TEXT,
        parent_note_id TEXT,
        url TEXT,
        owner_id TEXT,
        owner_name TEXT,
        review_state TEXT,
        note_type TEXT,
        summary TEXT,
        synced_at TEXT DEFAULT CURRENT_TIMESTAMP,
        deleted_at TEXT,
        is_deleted INTEGER DEFAULT 0,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP,
        updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
        last_edited_at TEXT
      , summary_updated_at TEXT);

-- tartarus_object_history
CREATE TABLE IF NOT EXISTS tartarus_object_history (
      id BIGSERIAL PRIMARY KEY,
      object_uuid TEXT NOT NULL,
      version INTEGER NOT NULL,
      snapshot TEXT NOT NULL,
      changed_by TEXT DEFAULT 'system',
      change_summary TEXT,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (object_uuid) REFERENCES tartarus_objects(uuid) ON DELETE CASCADE
    );

-- tartarus_objects
CREATE TABLE IF NOT EXISTS tartarus_objects (
      uuid TEXT PRIMARY KEY,
      type TEXT NOT NULL,
      source_table TEXT NOT NULL,
      source_id TEXT NOT NULL,
      title TEXT,
      summary TEXT,
      tags TEXT DEFAULT '[]',
      importance INTEGER DEFAULT 0,
      estimated_tokens INTEGER DEFAULT 0,
      created_at TEXT DEFAULT CURRENT_TIMESTAMP,
      updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(source_table, source_id)
    );

-- work_experience
CREATE TABLE IF NOT EXISTS work_experience (
      id TEXT PRIMARY KEY,
      title TEXT NOT NULL,
      company TEXT NOT NULL,
      department TEXT,
      location TEXT NOT NULL,
      dateStart TEXT NOT NULL,
      dateEnd TEXT,
      tagline TEXT NOT NULL,
      note TEXT,
      achievements TEXT DEFAULT '[]'
    , logo TEXT, summary TEXT, summary_updated_at TEXT);

